package wybs.lang;

import java.util.List;
import java.util.Set;

import wyfs.lang.Content;

/**
 * <p>
 * Provides a high-level schema for transforming files of a source type into
 * files of a target type. This may involved multiple tasks which can produce a
 * series of intermediate files.
 * </p>
 * 
 * <p>
 * Build platforms are not associated with projects per se; rather, they are
 * used to ensure the appropriate build rules are added to a given project. In
 * some sense, they are template for constructing appropriate build projects.
 * </p>
 * 
 * <p>
 * One build platform may depend on another. What this means is that, to
 * instantiate this platform on a given project, the dependent platforms must
 * also be instantiated. The build system is responsible for ensuring this
 * happens. Note, however, that the notion of source, target and intermediate
 * file is determined by the outer platform. Typically, this means the targets
 * for dependent platforms are treated as intermediate files.
 * </p>
 * <p>
 * A build platform is instantiated exactly once on a given project. This is
 * important when two or more platforms depend on the same platform to prevent
 * duplicate instantations.
 * </p>
 * 
 * @author David J. Pearce
 * 
 */
public interface BuildPlatform {

	/**
	 * The unique identifier for this platform through which it can be referred.
	 * 
	 * @return
	 */
	public String id();
	
	/**
	 * The type of source files handled by this task.
	 * 
	 * @return
	 */
	public Content.Type<?> sourceType();

	/**
	 * The type target files generated by this task.
	 * @return
	 */
	public Content.Type<?> targetType();

	/**
	 * The list of all intermediate types generated by this task. This may
	 * be empty (though not null) if no intermediate files are produced.
	 * Knowledge of the intermediate files is important, as it allows one to
	 * expose them for e.g. debugging purposes.
	 * 
	 * @return
	 */
	public List<Content.Type<?>> intermediateTypes();
	
	/**
	 * The set of builders used by this platform. These are identifiers
	 * referring to specific instances of the wybs.Builder extension point.
	 * 
	 * @return
	 */
	public Set<String> builders();

	/**
	 * The set of platforms on which this platform depends. These are
	 * identifiers referring to specific instances of the wybs.Platform
	 * extension point.
	 * 
	 * @return
	 */
	public Set<String> dependents();
}
