package wybs.lang;

import java.util.List;
import java.util.Set;

import wyfs.lang.Content;

/**
 * A build task provides a schema for transforming files of one type into
 * files of another type. This is distinct from a "builder", in that it may
 * involve multiple intermediate steps.
 * 
 * @author David J. Pearce
 * 
 */
public interface Platform {

	/**
	 * The unique identifier for this platform through which it can be referred.
	 * 
	 * @return
	 */
	public String id();
	
	/**
	 * The type of source files handled by this task.
	 * 
	 * @return
	 */
	public Content.Type<?> sourceType();

	/**
	 * The type target files generated by this task.
	 * @return
	 */
	public Content.Type<?> targetType();

	/**
	 * The list of all intermediate types generated by this task. This may
	 * be empty (though not null) if no intermediate files are produced.
	 * Knowledge of the intermediate files is important, as it allows one to
	 * expose them for e.g. debugging purposes.
	 * 
	 * @return
	 */
	public List<Content.Type<?>> intermediateTypes();
	
	/**
	 * The set of builders used by this platform. These are identifiers
	 * referring to specific instances of the wybs.Builder extension point.
	 * 
	 * @return
	 */
	public Set<String> builders();

	/**
	 * The set of platforms on which this platform depends. These are
	 * identifiers referring to specific instances of the wybs.Platform
	 * extension point.
	 * 
	 * @return
	 */
	public Set<String> dependents();
}
